### ISSUE TITLE
 Failed to get ENTRIES for log got HTTP Status "429 Too Many Requests"

### ISSUE THREAD

**Issue by byte-sec** [g0ldencybersec/gungnir#2]
HI there, I hope you are sound and save . Actually i've got an issue while using the gungnir tool i'll be happy if you help . The description is given below:

![image](https://github.com/g0ldencybersec/gungnir/assets/130414280/e2a63abf-d62f-44bd-960a-783267c1c301)
 

The tool is showing too many requests and not returning anything , Please look into this issue thanks!

**Comment by g0ldencybersec** [comment]
Sorry never answered/closed this. But this has been handled in newer versions now :)
