### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Muhammad-Tayab** [g0ldencybersec/gungnir#3]
when i run the tool this is the output 
panic: failed to get log list data: Get "https://www.gstatic.com/ct/log_list/v3/all_logs_list.json": dial tcp [2a00:1450:4019:807::2003]:443: connect: network is unreachable

goroutine 1 [running]:
github.com/g0ldencybersec/gungnir/pkg/runner.NewRunner(0xc0000241c0)
	/home/haxor/go/pkg/mod/github.com/g0ldencybersec/gungnir@v1.0.8/pkg/runner/runner.go:64 +0x292
main.main()
	/home/haxor/go/pkg/mod/github.com/g0ldencybersec/gungnir@v1.0.8/cmd/gungnir/main.go:311 +0x18

**Comment by meme-lord** [comment]
Seems like a networking issue on your end.
Can you curl the url? ```curl https://www.gstatic.com/ct/log_list/v3/all_logs_list.json```
Could also be because your network doesnt support ipv6 but the program is trying to load the url over ipv6 for some reason?

**Comment by Muhammad-Tayab** [comment]
Thank you for replying, yes curl https://www.gstatic.com/ct/log_list/v3/all_logs_list.json is working. 
yes may be my network don't support ipv6. can you guide me how can i add ipv6 support or some other way around it
