### ISSUE TITLE
Output messages to STDERR instead of STDOUT

### ISSUE THREAD

**Issue by xnl-h4ck3r** [g0ldencybersec/gungnir#4]
Hey!
When you cancel gungnir, it wirtes the following comments to STDOUT:
Shutdown signal received
Gracefully shutdown all routines

Can these be written to STDERR instead so that they don' t get written to the file when I run `gungnir -r input.txt > output.txt`?

**Comment by g0ldencybersec** [comment]
Ya I changed it and pushed it to the newest version 1.0.9 :) Should be working now let me know!

**Comment by xnl-h4ck3r** [comment]
Thanks!!
